services:
  api:
    build: .
    container_name: task_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_pass_2026
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
