[project]
name = "task-app"
version = "0.1.0"
description = ""
authors = [
    {name = "None"}
]
requires-python = "^3.11"
dependencies = [
    "fastapi (>=0.141.1,<0.142.0)",
    "uvicorn[standard] (>=0.52.4,<0.53.0)",
    "python-jose[cryptography] (>=3.5.0,<4.0.0)",
    "sqlalchemy (>=2.0.52,<3.0.0)",
    "psycopg2-binary (>=2.9.12,<3.0.0)",
    "pydantic (>=2.13.4,<3.0.0)",
    "python-dotenv (>=1.2.3,<2.0.0)",
    "pydantic-settings (>=2.15.0,<3.0.0)",
    "httpx2 (>=2.12.0,<3.0.0)",
    "passlib[bcrypt] (>=1.7.4,<2.0.0)",
    "bcrypt (==4.0.1)",
    "python-multipart (>=0.0.32,<0.0.33)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "coverage[toml] (>=7.15.4,<8.0.0)"
]
